name: Push (main)

on:
  push:
    branches:
      - main
      - stable/2023.2

jobs:
  test-python:
    uses: ./.github/workflows/test-python.yml
  test-golang:
    uses: ./.github/workflows/test-golang.yml
  build-microcluster:
    uses: ./.github/workflows/build-golang.yml
  build:
    uses: ./.github/workflows/build-snap.yml
